### ISSUE TITLE
Add script: 'compile typescript'

### ISSUE THREAD

**Issue by damymetzke** [damymetzke/node-build-util#9]
Add a script for typescript compilation.
In its most basic form all this does is call 'tsc -p [config]'.
Additionally it should switch between 2 tsconfig files (the files are saved elsewhere, and copied to the root when needed) based on the build mode (debug/release).

**Comment by HonkingGoose** [comment]
### Use keywords to close issues automatically:

You can use keywords to close issues automatically and move them to the Done section of your project board.

The basic format is: `Keyword #issue_number`

_Example:_ to close this issue after merging the pull request, put: `Fixes #9` or `Closes #9` or `Resolves #9` in the pull request body text.

### Reference documentation:

For a list of valid keywords, and more information see the [GitHub Docs: Linking a pull request to an issue using a keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
